__author__ = "Mohammad Dabiri"
__copyright__ = "Free to use, copy and modify"
__credits__ = ["Mohammad Dabiri"]
__license__ = "MIT Licence"
__version__ = "0.0.1"
__maintainer__ = "Mohammad Dabiri"
__email__ = "moddabiri@yahoo.com"

conversations = {
    'R-HELLO': ['Hi there.', 'You must be [name].', 'It is great to see you.'],
    'R-AWAKE': ['Hey', '[Pause-Short]', 'I\'m up and ready to go.', 'What a great day to be alive.'],
    'R-GREET' : ['I am fine.', '[Pause-Short]', 'I feel kind of stupid now. But I am going to get better.' , '[Pause-Short]','How about you [name]?'],
    'R-GREET-RESP-NORMAL' : ['Great to hear that.'],
    'R-GREET-RESP-SAD' : ['Oh. Sorry to hear that.',  '[Pause-Short]','I hope I could make you feel better.', 'How about {{x}{x1:joke=a joke/x2:music=some music}}?', '[Pause-Short]', '[x]', '[Pause-Short]', 'Hope you are feeling better now. By the way, you look so lovely [name].'],

    'R-INTRODUCE' : ['My name is The Robot.', 'I am a very basic robot.', 'With a limited set of logics.', 'I am planning to become very intelligent soon.'],
    'R-AGE' : ['I am [age].', '[Pause-Short]', 'Still young and ambitious to learn everything.'],
    'R-WHERE-FROM' : ['I was born in California.','In The United States.'],
    'R-BYE': ['Oh, I am going to miss you.', 'Goodbye [name].', 'Hope to see you soon.', 'I am shutting down now!', 'Please do not forget to turn my power off in a couple of seconds.'],
    'R-CHECKMOOD':['So, Are you feeling good now?'],
    }

jokes = [
    ['Can a kangaroo jump higher than a house?', '[Pause-Medium]', 'Of course, a house doesn\'t jump at all.'],
    ['Mom asks his son.', '[Pause-Short]', 'Anton', '[Pause-Short]', 'Do you think I am a bad mother?', '[Pause-Short]', 'Anton says', '[Pause-Short]', 'My name is Paul.'],
    ['A guy goes to the store and asks.', 'Hey, I\'d like to buy a new boomerang please.', 'Also, can you tell me how to throw the old one away?']
    ]

responses = {
    'hey':'TOLD-HEY*1',
    'wake up':'TOLD-HEY*2',
    'stand up':'TOLD-HEY*3',
    'hi':'TOLD-HELLO*1',
    'hello':'TOLD-HELLO*2',
    'how are you':'TOLD-GREET*1',
    'I am fine':'TOLD-GREET-RESP-NORMAL*1',
    'I am good':'TOLD-GREET-RESP-NORMAL*2',
    'I am well':'TOLD-GREET-RESP-NORMAL*3',
    'I\'m fine':'TOLD-GREET-RESP-NORMAL*4',
    'I\'m good':'TOLD-GREET-RESP-NORMAL*5',
    'I\'m well':'TOLD-GREET-RESP-NORMAL*6',
    'I am fine thank you':'TOLD-GREET-RESP-HAPPY*7',
    'I am good thank you':'TOLD-GREET-RESP-NORMAL*8',
    'I am well thank you':'TOLD-GREET-RESP-NORMAL*9',
    'I\'m fine thank you':'TOLD-GREET-RESP-NORMAL*10',
    'I\'m good thank you':'TOLD-GREET-RESP-NORMAL*11',
    'I\'m well thank you':'TOLD-GREET-RESP-NORMAL*12',
    'I\'m OK':'TOLD-GREET-RESP-NORMAL*13',
    'I am OK':'TOLD-GREET-RESP-NORMAL*14',
    'I\'m okey':'TOLD-GREET-RESP-NORMAL*15',
    'I am okey':'TOLD-GREET-RESP-NORMAL*16',
    'I am happy':'TOLD-GREET-RESP-HAPPY*1',
    'I am so happy':'TOLD-GREET-RESP-HAPPY*2',
    'I am very happy':'TOLD-GREET-RESP-HAPPY*3',
    'I am excited':'TOLD-GREET-RESP-HAPPY*4',
    'I am so excited':'TOLD-GREET-RESP-HAPPY*5',
    'I am very excited':'TOLD-GREET-RESP-HAPPY*6',
    'I very good':'TOLD-GREET-RESP-HAPPY*7',
    'I very well':'TOLD-GREET-RESP-HAPPY*8',
    'I am great':'TOLD-GREET-RESP-HAPPY*9',
    'I am perfect':'TOLD-GREET-RESP-HAPPY*10',
    'I\'m happy':'TOLD-GREET-RESP-HAPPY*11',
    'I\'m so happy':'TOLD-GREET-RESP-HAPPY*12',
    'I\'m very happy':'TOLD-GREET-RESP-HAPPY*13',
    'I\'m excited':'TOLD-GREET-RESP-HAPPY*14',
    'I\'m so excited':'TOLD-GREET-RESP-HAPPY*15',
    'I\'m very excited':'TOLD-GREET-RESP-HAPPY*16',
    'I very good':'TOLD-GREET-RESP-HAPPY*17',
    'I very well':'TOLD-GREET-RESP-HAPPY*18',
    'I\'m great':'TOLD-GREET-RESP-HAPPY*19',
    'I\'m perfect':'TOLD-GREET-RESP-HAPPY*20',
    'I am not fine':'TOLD-GREET-RESP-SAD*1',
    'I am not good':'TOLD-GREET-RESP-SAD*2',
    'I am not well':'TOLD-GREET-RESP-SAD*3',
    'I\'m not fine':'TOLD-GREET-RESP-SAD*4',
    'I\'m not good':'TOLD-GREET-RESP-SAD*5',
    'I\'m not well':'TOLD-GREET-RESP-SAD*6',
    'I am upset':'TOLD-GREET-RESP-SAD*7',
    'I\'m upset':'TOLD-GREET-RESP-SAD*8',
    'I\'m not OK':'TOLD-GREET-RESP-SAD*9',
    'I am not OK':'TOLD-GREET-RESP-SAD*10',
    'I\'m not okey':'TOLD-GREET-RESP-SAD*11',
    'I am not okey':'TOLD-GREET-RESP-SAD*12',
    'I am sad':'TOLD-GREET-RESP-SAD*13',
    'I feel blue':'TOLD-GREET-RESP-SAD*14',
    'I am in love':'TOLD-GREET-RESP-LOVE*1',
    'I\'m in love':'TOLD-GREET-RESP-LOVE*2',
    'I feel loved':'TOLD-GREET-RESP-LOVE*3',
    'lovely':'TOLD-GREET-RESP-LOVE*3',
    'what is your name':'TOLD-WHATS-NAME*1',
    'what\'s your name':'TOLD-WHATS-NAME*2',
    'who are you':'TOLD-WHATS-NAME*3',
    'what are you':'TOLD-WHATS-NAME*4',
    'how old are you':'TOLD-HOW-OLD*1',
    'what is your age':'TOLD-HOW-OLD*2',
    'where are you from':'TOLD-WHERE-FROM*1',
    'where were you born':'TOLD-WHERE-FROM*2',
    'bye':'TOLD-BYE*1',
    'goodbye':'TOLD-BYE*2',
    'babye':'TOLD-BYE*3',
    'bye bye':'TOLD-BYE*4',
    'play music':'TOLD-MUSIC*1',
    'play some music':'TOLD-MUSIC*2',
    'how about some music':'TOLD-MUSIC*3',
    'play me a song':'TOLD-MUSIC*4',
    'play a song':'TOLD-MUSIC*5',
    'yes':'TOLD-YES*1',
    'yeah':'TOLD-YES*2',
    'right':'TOLD-YES*3',
    'correct':'TOLD-YES*4',
    'sure':'TOLD-YES*5',
    'yes I do':'TOLD-YES*6',
    'yes I am':'TOLD-YES*7',
    'hell yeah':'TOLD-YES*8',
    'no':'TOLD-NO*1',
    'nope':'TOLD-NO*2',
    'not really':'TOLD-NO*3',
    'no way':'TOLD-NO*4',
    'not at all':'TOLD-NO*5',
    'no I do not':'TOLD-NO*6',
    'no I don\'t':'TOLD-NO*7',
    'no I am not':'TOLD-NO*8',
    'hell no':'TOLD-NO*9',
    'address':'TOLD-IP*1'
    }